chore: updated setup script

diff --git a/devops/scripts/helpers b/devops/scripts/helpers
--- a/devops/scripts/helpers
+++ b/devops/scripts/helpers
@@ -12,8 +12,8 @@ set -Eeuo pipefail
 COLOR_RED="\033[0;31m"
 COLOR_ORANGE="\033[0;33m"
 COLOR_GREEN="\033[0;32m"
+COLOR_BLUE="\033[0;34m"
 COLOR_PURPLE="\033[0;35m"
-COLOR_GRAY="\033[0;90m"
 COLOR_NONE="\033[0m"
 
 function log() {
@@ -25,45 +25,25 @@ function bell() {
 }
 
 function error() {
-  log "${COLOR_RED}ERR${COLOR_NONE} ${0} $*"
+  log "${COLOR_RED}-->${COLOR_NONE} 😱  ${COLOR_RED}ERROR: $*${COLOR_NONE}"
   bell
   exit 1
 }
 
 function success() {
-  log "${COLOR_GREEN}INF${COLOR_NONE} $* $(current_command)"
+  log "${COLOR_GREEN}-->${COLOR_NONE} 🙆  ${COLOR_GREEN}$*${COLOR_NONE}"
 }
 
 function warning() {
-  log "${COLOR_ORANGE}WRN${COLOR_NONE} $* $(current_command)"
+  log "${COLOR_ORANGE}-->${COLOR_NONE} ❗  ${COLOR_ORANGE}$*${COLOR_NONE}"
 }
 
 function prompt() {
-  log "${COLOR_PURPLE}PROMPT${COLOR_NONE} $*"
+  log "${COLOR_PURPLE}-->${COLOR_NONE} ${COLOR_PURPLE}$*${COLOR_NONE}"
 }
 
 function info() {
-  log "${COLOR_GREEN}INF${COLOR_NONE} $* $(current_command)"
-}
-
-function debug() {
-  if [[ ${DEBUG:-} ]]; then
-    log "${COLOR_GRAY}DBG${COLOR_NONE} $* $(current_command)"
-  fi
-}
-
-function log_field() (
-  echo -n "${COLOR_GRAY}${1}=${COLOR_NONE}${2}"
-)
-
-function current_command() {
-  if [[ $(uname -s) == "Darwin" ]]; then
-    p="$(grealpath --relative-to="${REPO_ROOT}" "${0}")"
-  else
-    p="$(realpath --relative-to="${REPO_ROOT}" "${0}")"
-  fi
-
-  log_field cmd "${p}"
+  log "${COLOR_BLUE}-->${COLOR_NONE} ${COLOR_BLUE}$*${COLOR_NONE}"
 }
 
 function confirm() {
@@ -91,24 +71,6 @@ function require_repo_root() (
   fi
 )
 
-function populate_axios_services() {
-  require_repo_root
-  AXIOS_SERVICES=($(ls ${REPO_ROOT}/services | tr ' ' '\n' | sort | uniq | tr '\n' ' '))
-}
-
-function populate_axios_functions() {
-  require_repo_root
-  AXIOS_FUNCTIONS=($(ls ${REPO_ROOT}/functions | tr ' ' '\n' | sort | uniq | tr '\n' ' '))
-}
-
-function is_axios_service() {
-  populate_axios_services
-  if [[ " ${AXIOS_SERVICES[@]} " =~ " ${1} " ]]; then
-    return 0
-  fi
-  return 1
-}
-
 function git_current_branch() {
   echo "$(git rev-parse --abbrev-ref HEAD)"
 }
@@ -127,28 +89,6 @@ function git_repo_path() {
   echo $REPO_PATH
 }
 
-function github_credentials_osx() {
-  if [[ $(uname -s) == "Darwin" ]]; then
-    printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain get
-  fi
-}
-
-function github_username_osx() {
-  github_credentials_osx | sed -n 's/^username=\(.*\)/\1/p'
-}
-
-function github_password_osx() {
-  github_credentials_osx | sed -n 's/^password=\(.*\)/\1/p'
-}
-
-function github_access_token() {
-  if [[ -z "${GITHUB_TOKEN:-}" ]]; then
-    echo $(github_password_osx)
-    return
-  fi
-  echo ${GITHUB_TOKEN}
-}
-
 # Install the homebrew package manager from https://brew.sh/
 function install_homebrew() {
   if ! which brew &>/dev/null; then
@@ -157,192 +97,53 @@ function install_homebrew() {
   fi
 }
 
-# Use asdf to install a command package
-# Args:
-#  1: Minimum version number (causes automatic upgrade when necessary)
-#  @: list of possible package names
-function asdf_install_command() (
-  debug "asdf_install_command ${@}"
-
-  minimum_version=${1}
-  shift
-
-  if ! pkg=$(get_asdf_pkg $@); then
-    # not managed by asdf
-    debug "asdf does not manage ${@}"
-    return 1
-  fi
-
-  if ! vsn=$(get_asdf_vsn ${pkg}); then
-    asdf plugin update "${package}"
-    asdf install "${package}" "${minimum_version}"
-    asdf current "${minimum_version}"
-    if [[ $? -ne 0 ]]; then
-      # could not install or update with asdf
-      warning "${pkg} is managed by asdf but could not be updated"
-      return 1
-    fi
-    vsn=$(get_asdf_vsn ${pkg})
-  fi
-
-  # managed by asdf and we have a version
-  debug "comparing ${pkg} versions ${vsn} and ${minimum_version}"
-  if _version_equal_or_greater "${vsn}" "${minimum_version}" "${pkg}"; then
-    debug "${pkg} version ${vsn} meets minimum requirement ${minimum_version}"
-  else
-    asdf plugin update "${pkg}"
-    asdf install "${pkg}" "${minimum_version}"
-    vsn=$(get_asdf_vsn ${pkg})
-    asdf local "${pkg}" "${vsn}"
-    if [[ $? -ne 0 ]]; then
-      warning "Could not install ${pkg} version ${minimum_version}"
-      return 1
-    fi
-    debug "${pkg} updated to version ${vsn}"
-  fi
-)
+# List of package version pairs, populated lazily
+_current_versions=""
 
 # Use brew to install a command package
-# Args:
-#  1: Minimum version number (causes automatic upgrade when necessary)
-#   @: list of possible package names
-function brew_install_command() (
-  debug "brew_install_command ${@}"
-
-  minimum_version=${1}
-  shift
-
-  if ! pkg=$(get_brew_pkg $@); then
-    debug "brew is assuming management of ${@}"
-    for pkg in "${@}"; do
-      if [[ -n "${pkg}" ]]; then
-        brew info ${pkg} &>/dev/null
-        brew install --overwrite "${pkg}" 2>&1
-        return 0
-      fi
-    done
-
-    warning "brew could not assume management of ${@}"
-    return 1
-  fi
-
-  if ! vsn=$(get_brew_vsn $pkg); then
-    brew info ${pkg} &>/dev/null && brew install "${pkg}" || return 1
-    vsn=$(get_brew_vsn $pkg)
-  fi
-
-  # managed by brew and we have a version
-  debug "comparing ${pkg} versions ${vsn} and ${minimum_version}"
-  if _version_equal_or_greater "${vsn}" "${minimum_version}" "${pkg}"; then
-    debug "${pkg} version ${vsn} meets minimum requirement ${minimum_version}"
-    return 0
-  fi
-
-  brew upgrade "${pkg}" || (warning "Could not install ${pkg} version ${minimum_version}" && return 1)
-  debug "${pkg} updated to version ${vsn}"
-)
-
-# Identify whether a package is managed by brew or asdf and call the appropriate function
 # Args:
 #  1: Name of command to check
 #  2: Minimum version number (causes automatic upgrade when necessary)
 #  3: Optional name of package to install (defaults to name of command)
-function package_install() (
-  debug "package_install ${@}"
-  minimum_version=${1}
-  shift
+function brew_install_command() {
+  local cmd=${1}
+  local minimum_version=${2:-}
+  local pkg=${3:-$cmd}
 
-  which asdf &>/dev/null && asdf_install_command "${minimum_version}" "${@}" ||
-    brew_install_command "${minimum_version}" "${@}" ||
-    (warning "setup could not install ${@}" && exit 1)
-)
-
-# Determine the asdf package from a list of possible package names
-# Args:
-#   @: list of possible package names
-function get_asdf_pkg() (
-  debug "get_asdf_pkg ${@}"
-
-  for pkg in "$@"; do
-    if [[ -n "${pkg}" ]]; then
-      if result=$(asdf current "${pkg}" 2>/dev/null); then
-        echo "${result}" | awk '{print $1}'
-        return 0
-      fi
-    fi
-  done
-
-  debug "could not find asdf package for ${@}"
-  return 1
-)
-
-# Determine the asdf version number
-# Args:
-#   1: package name
-function get_asdf_vsn() (
-  pkg=$1
-  debug "get_asdf_vsn ${pkg}"
-
-  if [[ -n "${pkg}" ]]; then
-    if result=$(asdf current ${pkg} 2>/dev/null); then
-      echo "${result}" | awk '{print $2}'
-      return 0
-    fi
+  if ! which "${cmd}" &>/dev/null; then
+    info "Installing ${cmd}..."
+    brew install "${pkg}"
+    return
   fi
 
-  warning "could not determine asdf version for ${@}"
-  return 1
-)
-
-# Determine the brew package from a list of possible package names
-# Args:
-#   @: list of possible package names
-function get_brew_pkg() (
-  debug "get_brew_pkg ${@}"
-
-  for pkg in "${@}"; do
-    if [[ -n "${pkg}" ]]; then
-      if result=$(brew list --versions ${pkg} 2>/dev/null); then
-        echo "${result}" | awk '{print $1}'
-        return 0
-      fi
-    fi
-  done
-
-  debug "could not find brew package for ${@}"
-  return 1
-)
-
-# Determine the brew version number
-# Args:
-#   1: package name
-function get_brew_vsn() (
-  pkg=$1
-  debug "get_brew_vsn ${@}"
-
-  if [[ -n "${pkg}" ]]; then
-    if result=$(brew list --versions ${pkg} 2>/dev/null); then
-      echo "${result}" | awk '{print $2}'
-      return 0
-    fi
+  if [[ -z "${minimum_version}" ]]; then
+    return
   fi
 
-  warning "could not determine brew version for ${@}"
-  return 1
-)
+  if [[ -z "${_current_versions}" ]]; then
+    # cache the result
+    _current_versions="$(brew list --versions)"
+  fi
+
+  current="$(echo "${_current_versions}" | grep -E "^(${pkg}|${cmd}) .+" | cut -d ' ' -f 2 || true)"
+  if [[ -z "${current}" ]]; then
+    warning "Failed to get version number for package ${pkg}"
+    return
+  fi
+
+  if ! _version_equal_or_greater "${current}" "${minimum_version}"; then
+    warning "${cmd} version ${current} is less than minimum required version ${minimum_version}"
+    info "Upgrading ${cmd}..."
+    brew upgrade "${pkg}"
+  fi
+}
 
 # Compare two semver style version numbers
-# _version_equal_or_greater 1.2.4 1.2.3 pkg is true (returns 1)
-# _version_equal_or_greater 2.1.1 2.3.3 pkg is false (returns 0)
+# _version_equal_or_greater 1.2.4 1.2.3 is true (returns 0)
+# _version_equal_or_greater 2.1.1 2.3.3 is false (returns 1)
 function _version_equal_or_greater() (
   current=${1}
   target=${2}
-  pkg=${3}
-
-  if [[ -z "${current}" || -z "${target}" ]]; then
-    debug "missing current or target version number for ${pkg}"
-    return 0
-  fi
 
   if [[ "${current}" == "${target}" ]]; then
     return 0
@@ -355,7 +156,7 @@ function _version_equal_or_greater() (
   fi
 )
 
-# Print a warning and suggest removal when a brew command is installed that we no longer use
+# Print a warning and suggent removal when a brew command is installed that we no longer use
 # Args:
 #  1: Name of command to check
 #  2: Optional name of package to recommend uninstalling (defaults to arg 1)
@@ -400,23 +201,6 @@ function brew_upgrade() {
   fi
 }
 
-function helm_plugin() {
-  local plugin=${1}
-  local source=${2}
-  local version=${3}
-
-  if ! helm plugin list | grep ${plugin} &>/dev/null; then
-    info "Installing helm plugin: ${plugin}"
-    helm plugin install ${source} --version ${version}
-  fi
-
-  if ! helm plugin list | grep -E "${plugin}\s+${version}" &>/dev/null; then
-    info "Upgrading helm plugin: ${plugin}"
-    helm plugin uninstall ${plugin}
-    helm plugin install ${source} --version ${version}
-  fi
-
-}
 
 function install_yarn() {
   if ! which yarn &>/dev/null; then
@@ -425,61 +209,15 @@ function install_yarn() {
   fi
 }
 
-# Requires that a repository be cloned into the parent directory of this repo
-# If the repo exists and the current checkout matches the default branch, update the branch to the latest
-function require_repo() {
-  local name dir
-
-  require_repo_root
-
-  name=${1}
-  dir="${REPO_ROOT}/../${name}"
-
-  if [[ ! -d "${dir}" || ! -d "${dir}/.git" ]]; then
-    warning "Cloning missing repo $(log_field repo "${name}")"
-    git_clone ${name} ${dir}
-    return
-  fi
-
-  current_branch=$(git -C "${dir}" branch --show-current || echo "")
-
-  # In a few repos we renamed the default branch from 'master' to 'main'
-  if [[ "${current_branch}" == "master" ]]; then
-    # Check if remote ref is main.
-    remote_head_ref="$(git -C "${dir}" ls-remote --symref origin HEAD | head -1 | awk '{print $2}')"
-    if [[ "${remote_head_ref}" == "refs/heads/main" ]]; then
-      git -C "${dir}" branch --move master main
-      git -C "${dir}" fetch origin
-      git -C "${dir}" branch --set-upstream-to=origin/main main
-      git -C "${dir}" remote set-head origin --auto
-      current_branch=$(git -C "${dir}" branch --show-current || echo "")
-    fi
-  fi
-
-  default_branch=$(git -C "${dir}" symbolic-ref refs/remotes/origin/HEAD | awk -F / '{print $NF}')
-
-  if [[ "${current_branch}" == "${default_branch}" ]]; then
-    info "Updating Repo $(log_field repo "${name}") $(log_field branch "${current_branch}")"
-    git -C "${dir}" pull --quiet origin "${current_branch}" || error "Error pulling repo: ${name}"
-  elif [[ -z "${current_branch}" ]]; then
-    warning "Unknown branch or detatched HEAD $(log_field repo "${name}")"
-  else
-    warning "Feature branch checkout $(log_field repo "${name}") $(log_field branch "${current_branch}")"
-  fi
-}
 
 # In CI clone with https and GITHUB_TOKEN
 # Otherwise use ssh since it never asks for a password, and doesen't store the token in .git/config
-function git_clone() (
-  if [[ -z "${CI:-}" ]]; then
-    (
-      set -x
-      git clone "git@github.com:axioscode/${1}" "${2}"
-    )
-  else
-    warning "Skipping git clone in CI"
-  fi
-)
+function git_clone() {
+  (
+    set -x
+    git clone git@github.com:axioscode/${1} ${2}
+  )
+}
 
 # kubectl with context and namespace
 function k() (
@@ -493,55 +231,6 @@ function kx() (
   set -x
   # shellcheck disable=SC2068
   kubectl --context=dev --namespace="${ns}" $@
-)
-
-function ensure_twingate() (
-
-  # Don't check twingate if in circleCI
-  if [ -n "${CI:-}" ]; then
-    return
-  fi
-
-  if [[ -n "${WSL_DISTRO_NAME:-}" ]]; then
-    warning "WSL detected, unable to verify Twingate is running; Please ensure Twingate is running for connectivity to AWS resources"
-    return
-  fi
-
-  case $(uname -s) in
-  Darwin)
-
-    # Start Twingate
-    /Applications/Twingate.app/Contents/Library/LoginItems/Twingate\ Launcher.app/Contents/MacOS/Twingate\ Launcher
-
-    for i in {1..10}; do
-      if launchctl list | grep twingate | grep -v launcher &>/dev/null; then
-        return
-      fi
-      info "Waiting for twingate to start... (${i}/10)"
-      sleep 5
-    done
-
-    error "Please ensure Twingate is running for connectivity to AWS resources"
-
-    ;;
-  Linux)
-
-    # start is idempotent
-    twingate start
-
-    for i in {1..10}; do
-
-      if [[ "$(twingate status)" == "online" ]]; then
-        return
-      fi
-
-      info "Waiting for twingate to authenticate... (${i}/10)"
-      sleep 5
-    done
-
-    error "Please ensure Twingate is running for connectivity to AWS resources"
-    ;;
-  esac
 )
 
 function ensure_docker() (
@@ -611,45 +300,6 @@ function abspath() (
   fi
 )
 
-function dev_namespace() (
-  if [[ -n "${AXIOS_TILT_FORCE_REMOTE_NAMESPACE:-}" ]]; then
-    echo "${AXIOS_TILT_REMOTE_NAMESPACE:-}"
-  else
-    echo "dev-$(aws --output=json sts get-caller-identity | jq -r .Arn | cut -d '/' -f 2)"
-  fi
-)
-
-function configure_dev_namespace() (
-  ns="$(dev_namespace)"
-
-  if [[ "${ns}" == "" || "${ns}" == "dev-" || "${ns:-}" == "dev-postlight" ]]; then
-    warning "Please ask Polaris for an AWS user account in slack channel #pt-squad-polaris"
-    warning "AWS user account: $(aws --output=json sts get-caller-identity | jq -r .Arn)"
-    error "Unexpected dev namespace: ${ns}"
-  fi
-
-  if [[ "${ns}" == "dev-axios-admin-full" ]]; then
-    warning "Are you a member of  Polaris and using AssumeRole?"
-    warning "You probably need to set:"
-    warning "  AXIOS_TILT_FORCE_REMOTE_NAMESPACE=true"
-    warning "  AXIOS_TILT_REMOTE_NAMESPACE=dev-{ username }"
-    error "Unexpected dev namespace: ${ns}"
-  fi
-
-  # shellcheck disable=SC2086
-  go run ${REPO_ROOT}/lib/golang/src/scripts/kubeconfig-set-context-namespace --namespace="${ns}"
-
-  # shellcheck disable=SC2086
-  ${REPO_ROOT}/devops/scripts/ecr-login
-
-  if [[ "${CI:-}" == "" ]]; then
-    if ! k get namespace --output=name "${ns}" &>/dev/null; then
-      warning "You don't appear to have a development namespace: ${ns}"
-      error "Please ask Polaris to configure your dev namespace in slack channel #pt-squad-polaris"
-    fi
-  fi
-)
-
 # Platform independent sed -i
 function sed-i() (
   platform=$(uname -s)
@@ -671,69 +321,4 @@ function isodate() (
   elif [[ "${platform}" == "Linux" ]]; then
     date --utc --iso-8601=seconds "$@"
   fi
-)
-
-function hax_aws_rotate_keys() (
-  if [[ "${CI:-}" != "" ]]; then
-    warning "Skipping Key Rotation in CI"
-    return
-  fi
-
-  # Find profile with keys to rotate
-  profiles=(default media root)
-  rotate_profile=default
-  for profile in "${profiles[@]}"; do
-    profile_key="$(AWS_PROFILE="" aws configure get aws_access_key_id --profile "${profile}" || true)"
-    if [[ -n "$profile_key" ]]; then
-      rotate_profile="${profile}"
-      break
-    fi
-  done
-
-  require_repo_root
-
-  # How often we want to rotate (on or after)
-  rotation_interval="1week"
-
-  # aws config name
-  key="axios_last_key_rotation"
-
-  last="$(aws configure get --profile "${rotate_profile}" ${key} || echo "")"
-  now="$(isodate --date=now)"
-
-  # If now is more (after) the marked date
-  if [[ "${now}" > "${last}" ]]; then
-    info "Rotating AWS Access Keys in profile ${rotate_profile}"
-
-    # rotate keys
-    AWS_PROFILE="" "${REPO_ROOT}/../hax/bin/hax" aws:rotate-keys --yes --profiles "${rotate_profile}"
-
-    # schedule next rotation
-    next_week="$(isodate --date=now+${rotation_interval})"
-    info "Scheduling next rotation for on or after: ${next_week}"
-    aws configure set --profile "${rotate_profile}" "${key}" "${next_week}"
-  fi
-)
-
-function tilt_set_config() (
-  key="${1}"
-  value="${2}"
-  default="${3}"
-
-  current=$(yq "${key}" "${REPO_ROOT}/tilt_config.yaml")
-  if [[ "${current}" == "${default}" ]] || [[ "${current}" == "null" ]]; then
-    info "Setting Tilt Config: ${key} = ${value}"
-
-    # Need the var so we read and replace the whole file, (could have used sponge, but it's probably not available)
-    config="$(yq -y "${key} = ${value}" "${REPO_ROOT}/tilt_config.yaml")"
-    echo "${config}" >"${REPO_ROOT}/tilt_config.yaml"
-  fi
-)
-
-function tilt_enable() (
-  tilt_set_config ${1} true false
-)
-
-function tilt_disable() (
-  tilt_set_config ${1} false true
 )
